#ifndef MENUPANEL_H
#define MENUPANEL_H

#include <wx/wx.h>
#include <wx/bitmap.h>
#include <array>
#include "UiHelpers.h"

class MainFrame;

/**
 * @brief Main menu panel for the bundl. launcher.
 *
 * This panel displays the launcher title, subtitle, and game navigation buttons.
 * It is responsible for drawing the themed menu background and forwarding menu actions back to the main frame.
 *
 * @author Aditi Bhardwaj
 */
class MenuPanel : public wxPanel
{
public:
    /**
     * @brief Constructs the menu panel.
     *
     * Creates the menu drawing state, loads the background image, binds mouse and paint events, and applies the initial theme.
     *
     * @param parent Pointer to the parent MainFrame.
     */
    MenuPanel(MainFrame *parent);

    /**
     * @brief Updates the panel theme mode.
     *
     * Stores the new theme setting, reapplies colours, and refreshes the panel.
     *
     * @param enabled True to enable dark mode, false otherwise.
     */
    void SetDarkMode(bool enabled);

private:
    /** @brief Number of painted menu buttons shown on the launcher screen. */
    static constexpr int buttonCount = 5;

    /** @brief Index for the Snake button. */
    static constexpr int snakeIndex = 0;

    /** @brief Index for the Connect Four button. */
    static constexpr int connectIndex = 1;

    /** @brief Index for the Anagrams button. */
    static constexpr int anagramsIndex = 2;

    /** @brief Index for the Settings button. */
    static constexpr int settingsIndex = 3;

    /** @brief Index for the Exit button. */
    static constexpr int exitIndex = 4;

    /** @brief Pointer to the owning main frame. */
    MainFrame *frame;

    /** @brief Background image used behind the menu panel. */
    wxBitmap backgroundBitmap;

    /** @brief Tracks whether dark mode is enabled. */
    bool darkMode = true;

    /** @brief Button bounds used for hit detection and drawing. */
    std::array<wxRect, buttonCount> buttonRects{};

    /** @brief Visual state for each painted menu button. */
    std::array<UiHelpers::PaintedButtonState, buttonCount> buttonStates{};

    /** @brief Index of the currently hovered button, or -1 if none. */
    int hoveredButton = -1;

    /** @brief Index of the currently pressed button, or -1 if none. */
    int pressedButton = -1;

    /**
     * @brief Applies the current theme to the painted menu.
     *
     * Refreshes the panel so the title, subtitle, and painted buttons redraw using the active light or dark mode.
     */
    void ApplyTheme();

    /**
     * @brief Updates the button rectangles to match the current panel size.
     *
     * Recomputes the layout for the five painted menu buttons inside the centered glass panel.
     */
    void LayoutButtonRects();

    /**
     * @brief Returns the index of the button under the given point.
     *
     * @param point The mouse position to test.
     * @return The matching button index, or -1 if the point is not inside any button.
     */
    int HitTestButton(const wxPoint &point) const;

    /**
     * @brief Clears the pressed state from all painted buttons.
     */
    void ClearPressedState();

    /**
     * @brief Clears the hovered state from all painted buttons.
     */
    void ClearHoveredState();

    /**
     * @brief Activates the menu action for the selected button index.
     *
     * @param buttonIndex The button that was clicked.
     */
    void ActivateButton(int buttonIndex);

    /**
     * @brief Handles repainting of the menu panel.
     *
     * Draws the scaled background image, the centered glass-style panel, the title and subtitle, and all painted menu buttons.
     *
     * @param event The paint event generated by wxWidgets.
     */
    void OnPaint(wxPaintEvent &event);

    /**
     * @brief Handles resizing of the menu panel.
     *
     * Recomputes button layout whenever the panel size changes.
     *
     * @param event The size event generated by wxWidgets.
     */
    void OnSize(wxSizeEvent &event);

    /**
     * @brief Handles mouse motion over the menu.
     *
     * Updates hover and pressed visual states for the painted buttons.
     *
     * @param event The mouse event.
     */
    void OnMouseMove(wxMouseEvent &event);

    /**
     * @brief Handles left mouse button presses on the menu.
     *
     * Marks a painted button as pressed when the mouse is pressed inside it.
     *
     * @param event The mouse event.
     */
    void OnLeftDown(wxMouseEvent &event);

    /**
     * @brief Handles left mouse button release on the menu.
     *
     * Activates a painted button if the press and release both happen inside the same button.
     *
     * @param event The mouse event.
     */
    void OnLeftUp(wxMouseEvent &event);

    /**
     * @brief Handles the mouse leaving the menu panel.
     *
     * Clears hover feedback when the pointer leaves the panel.
     *
     * @param event The mouse event.
     */
    void OnMouseLeave(wxMouseEvent &event);

    /**
     * @brief Handles activation of the Snake menu button.
     */
    void OnSnake();

    /**
     * @brief Handles activation of the Connect Four menu button.
     */
    void OnConnectFour();

    /**
     * @brief Handles activation of the Anagrams menu button.
     */
    void OnAnagrams();

    /**
     * @brief Handles activation of the settings menu button.
     */
    void OnSettings();

    /**
     * @brief Handles activation of the exit menu button.
     */
    void OnExit();
};

#endif
