#ifndef SETTINGSPANEL_H
#define SETTINGSPANEL_H

#include <wx/wx.h>
#include <wx/bitmap.h>

class MainFrame;
class MoodyButton;
class ToggleRow;

/**
 * @brief Settings panel for the bundl. launcher.
 *
 * This panel displays user preference controls for background music and dark mode.
 * It also handles returning to the main menu and draws the themed settings interface.
 *
 * @author Aditi Bhardwaj
 */
class SettingsPanel : public wxPanel
{
public:
    /**
     * @brief Constructs the settings panel.
     *
     * Creates the settings UI controls, loads the background image, binds interaction events, and applies the initial theme.
     *
     * @param parent Pointer to the parent MainFrame.
     */
    SettingsPanel(MainFrame *parent);

    /**
     * @brief Updates the panel theme mode.
     *
     * Stores the new dark mode setting, reapplies colours, and refreshes the settings view.
     *
     * @param enabled True to enable dark mode, false otherwise.
     */
    void SetDarkMode(bool enabled);

private:
    /** @brief Pointer to the owning main frame. */
    MainFrame *frame;

    /** @brief Background image used behind the settings panel. */
    wxBitmap backgroundBitmap;

    /** @brief Tracks whether dark mode is enabled. */
    bool darkMode = true;

    /** @brief Title text displayed at the top of the settings panel. */
    wxStaticText *titleText = nullptr;

    /** @brief Subtitle text displayed below the title. */
    wxStaticText *subtitleText = nullptr;

    /** @brief Toggle row controlling background music playback. */
    ToggleRow *musicToggle = nullptr;

    /** @brief Toggle row controlling dark mode state. */
    ToggleRow *darkModeToggle = nullptr;

    /** @brief Button used to return to the main menu. */
    MoodyButton *backButton = nullptr;

    /**
     * @brief Applies the current theme to all settings controls.
     *
     * Updates text and control colours to match the active light or dark mode.
     */
    void ApplyTheme();

    /**
     * @brief Handles repainting of the settings panel.
     *
     * Draws the scaled background image and the centered glass-style panel.
     *
     * @param event The paint event generated by wxWidgets.
     */
    void OnPaint(wxPaintEvent &event);

    /**
     * @brief Handles changes to the background music toggle.
     *
     * Starts or stops the launcher music depending on the toggle state.
     *
     * @param event The checkbox-style command event.
     */
    void OnToggleMusic(wxCommandEvent &event);

    /**
     * @brief Handles changes to the dark mode toggle.
     *
     * Updates the launcher theme and applies the new dark mode state.
     *
     * @param event The checkbox-style command event.
     */
    void OnToggleDarkMode(wxCommandEvent &event);

    /**
     * @brief Handles clicks on the back button.
     *
     * Requests that the main frame return to the main menu.
     *
     * @param event The button command event.
     */
    void OnBack(wxCommandEvent &event);
};

#endif